######################################################################
# Automatically generated by qmake (2.00a) Fri Apr 14 13:16:07 2006
######################################################################

TEMPLATE = app
TARGET += 
DEPENDPATH += .
INCLUDEPATH += . libmms /usr/include/libmms /usr/include/glib-2.0 /usr/lib/glib-2.0/include
CONFIG += release
LIBS += -lmms
QT -= gui

# Input
SOURCES += mimms.cpp
