.TH mimms2 1 "2008-04-06" "mms stream downloader"
.SH NAME
mimms2 \- mms (e.g. mms://) stream downloader
.SH SYNOPSIS
.BI "mimms2 [" options "] <" url "> [" filename "]"
.SH DESCRIPTION
mimms2 is a program designed to allow you to download streams using the
MMS protocol and save them to your computer, as opposed to watching them
live. mimms2 provides a convenient command-line interface, and can attain
high transfer rates by downloading in parallel.
.SH OPTIONS
.TP
.B "--version"
show program's version number and exit
.TP
.B "-h, --help"
show this help message and exit
.TP
.BI "-n " CONNECTIONS_COUNT ", --num-connections=" CONNECTIONS_COUNT
number of parallel connections to use.
.TP
.B "-c, --clobber"
automatically overwrite an existing file
.TP
.BI "-b " BANDWIDTH ", --bandwidth=" BANDWIDTH
the desired bandwidth for stream selection in BANDWIDTH bytes/s
.TP
.BI "-t " TIME ", --time=" TIME
stop downloading after TIME minutes
.TP
.B "-v, --verbose"
print verbose debug messages to stderr
.TP
.B "-q, --quiet"
don't print progress messages to stdout
.SH URLS
mimms2 supports only URLs that are supported by libmms, e.g. mms://, mmsh://, mmst://.
Previous versions tried to do fancy things with http:// URLs and .asx files, but this version does not (yet?) support that.
.SH AUTHOR
Wesley J. Landaker <wjl@icecavern.net>
